---
- name: Ensure config directory present
  file:
    path: "{{ config_dir }}"
    state: directory
    owner: cloudflared
    group: cloudflared
    mode: 0644

- name: Ensure credentials directory present
  file:
    path: "{{ config_dir }}/.credentials"
    state: directory
    owner: cloudflared
    group: cloudflared
    mode: 0644


- name: Get existing json credential, there is one
  find:
    paths: "{{ config_dir }}/.credentials"
    use_regex: yes
    patterns: ".*.json"
    recurse: yes
  register: search

- name: Look for credential in legacy folder
  find:
    paths: "/root/.cloudflared"
    use_regex: yes
    patterns: ".*.json"
    recurse: yes
  register: search
  when: search.matched != 1

- name: debug search
  debug:
    var: search
    verbosity: 1

- name: Block for if json credential does not exist
  block:
    - name: Run tunnel create
      command:
        cmd: cloudflared tunnel create {{ argo_hostname }}-{{ device }}
        chdir: "{{ config_dir }}"
      register: result
      changed_when: result.rc == 0

    - name: Extract tunnel certificate filename from create tunnel command
      find:
        paths: "{{ config_dir }}"
        use_regex: yes
        patterns: ".*.json"
        recurse: yes
      register: certjson

    - name: Assert that we have file
      assert:
        that: certjson is defined

    - name: debug filepaths
      debug:
        var: certjson
        verbosity: 1
      
    - name: Get uuid from filepath
      set_fact:
        argo_uuid: "{{ certjson['files'][0]['path'].split('/')[4].split('.')[0] }}"

    - name: debug uuid
      debug:
        var: argo_uuid
        verbosity: 1

    - name: Copy credential to credentials folder
      copy:
        remote_src: yes
        src: "{{ config_dir }}/{{ argo_uuid }}.json"
        dest: "{{ config_dir }}/.credentials/{{ argo_uuid }}.json"
        owner: cloudflared
        group: cloudflared
        mode: 0755
  when: search.matched == 0

- name: Block for if json credential does exist
  block:
    - name: Extract tunnel certificate filename
      find:
        paths: "{{ config_dir }}/.credentials"
        use_regex: yes
        patterns: ".*.json"
        recurse: yes
      register: certjson

    - name: Assert that we have file
      assert:
        that: certjson is defined

    - name: debug filepaths
      debug:
        var: certjson
        verbosity: 1
      
    - name: Get uuid from filepath
      set_fact:
        argo_uuid: "{{ certjson['files'][0]['path'].split('/')[4].split('.')[0] }}"

    - name: debug uuid
      debug:
        var: argo_uuid
        verbosity: 1
  when: search.matched == 1


- name: debug ingress var
  debug:
    var: ingress_rules
    verbosity: 1

- name: Template cloudflared config file
  template:
    src: config.yml.j2
    dest: "{{ config_dir }}/config.yml"
    owner: cloudflared
    group: cloudflared
    mode: 0755
    trim_blocks: no