---
- name: Check if file '{{ daemon_location }}' exists
  stat:
    path: "{{ daemon_location }}"
    checksum_algorithm: sha256
  register: stat_result

- name: Unarchive {{ download_baseurl }}/{{ cf_binary_filename }} to {{ install_target_dir }}
  unarchive:
    src: "{{ download_baseurl }}/{{ cf_binary_filename }}"
    dest: "{{ install_target_dir }}"
    remote_src: yes
  when: not stat_result.stat.exists or force_install

- name: Create {{ config_dir_tunnels }} if it does not exist
  file:
    path: "{{ config_dir_tunnels }}"
    state: directory
    owner: cloudflared
    group: cloudflared
    mode: 0755
