---
# tasks file for cloudflared
- name: Catch error block
  block:
    - name: Define required variables
      set_fact:
        daemon_location: "{{ install_target_dir }}/cloudflared"
        cf_binary_filename: "{{ cf_binaries[ansible_machine].filename_tgz }}"
        systemd_filename: "cloudflared"

    - name: Populate service facts
      service_facts:

    - name: Create cloudflared user
      user:
        name: cloudflared
        system: true
        state: present
        create_home: false
        groups: adm
        append: true
        shell: /usr/sbin/nologin
      when: not install_only

    - name: Download and install cloudflared
      include_tasks: install.yml
      when: install

    - name: Configuration tasks
      block:
      - name: Configure tunnel
        include_tasks: configure-tunnel.yml

      - name: Configure cloudflared
        include_tasks: configure.yml
      when: not install_only

    - name: Create DNS records
      command: "cloudflared tunnel --origincert {{ config_dir }}/.credentials/{{ cert_name }} route dns {{ argo_hostname }}-{{ device }} {{ item }}-{{ device }}-{{ argo_hostname}}.cstunnel.xyz"
      register: cloudflared_dns
      with_items:
        - ssh
        - services

    - name: debug dns request
      debug:
        var: cloudflared_dns

    - name: Secure tunnel
      include_tasks: secure.yml

    - name: Remove cert
      file:
        path: "{{ config_dir }}/.credentials/{{ cert_name }}"
        state: absent
  rescue:
    - name: Remove cert if errors
      file:
        path: "{{ config_dir }}/.credentials/{{ cert_name }}"
        state: absent