---
- name: POST access application for ssh
  uri:
    url: https://api.cloudflare.com/client/v4/accounts/{{ api_key }}/access/apps
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ api_secret }}
    body:
      name: "{{ argo_hostname.upper() }} {{ device.upper() }} SSH"
      domain: "ssh-{{ device }}-{{ argo_hostname }}.cstunnel.xyz"
      allowed_idps: "{{ allowed_idps }}"
      session_duration: "{{ session_duration }}"
    method: POST
    body_format: json
    status_code: [200, 201]
  register: post_ssh_access_res

- name: POST access application for services
  uri:
    url: https://api.cloudflare.com/client/v4/accounts/{{ api_key }}/access/apps
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ api_secret }}
    body:
      name: "{{ argo_hostname.upper() }} {{ device.upper() }} SERVICES"
      domain: "services-{{ device }}-{{ argo_hostname }}.cstunnel.xyz"
      allowed_idps: "{{ allowed_idps }}"
      session_duration: "{{ session_duration }}"
    method: POST
    body_format: json
    status_code: [200, 201]
  register: post_services_access_res

- name: Extract ids from post responses
  set_fact:
    ssh_uid: "{{ post_ssh_access_res.json.result.uid }}"
    services_uid: "{{ post_services_access_res.json.result.uid }}"

- name: POST policies for services
  uri:
    url: https://api.cloudflare.com/client/v4/accounts/{{ api_key }}/access/apps/{{ services_uid }}/policies
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ api_secret }}
    body: >-
      {"decision": "{{ item.key }}",
        "name": "{{ item.value.name }}",
        "include": {{ item.value.include }},
        "precedence": {{ item.value.precedence | int }},
        "exclude": {{ item.value.exclude }},
        "require": {{ item.value.require }}}
    method: POST
    status_code: [200, 201]
    body_format: json
  register: post_services_policy_resp
  loop: "{{ decisions | dict2items }}"

- name: POST policies for ssh
  uri:
    url: https://api.cloudflare.com/client/v4/accounts/{{ api_key }}/access/apps/{{ ssh_uid }}/policies
    headers:
      Content-Type: application/json
      Authorization: Bearer {{ api_secret }}
    body: >-
      {"decision": "{{ item.key }}",
        "name": "{{ item.value.name }}",
        "include": {{ item.value.include }},
        "precedence": {{ item.value.precedence | int }},
        "exclude": {{ item.value.exclude }},
        "require": {{ item.value.require }}}
    method: POST
    status_code: [200, 201]
    body_format: json
  register: post_ssh_policy_resp
  loop: "{{ decisions | dict2items }}"
